name: Linting

on: [pull_request]

jobs:

  shellcheck:
    name: Shell
    runs-on: ubuntu-latest
    steps:
    -
      uses: actions/checkout@v2
    -
      name: shellcheck
      uses: reviewdog/action-shellcheck@v1
      with:
        github_token: ${{ secrets.github_token }}
        reporter: github-pr-review
